final products = [
  {
    'id': '0',
    'title': 'Men\'s Nike Shoes',
    'price': 44.52,
    'imageUrl': 'assets/images/image_1.png',
    'company': 'Nike',
    'sizes': [9, 10, 11, 12],
  },
  {
    'id': '1',
    'title': 'Addidas Shoes',
    'price': 20.12,
    'imageUrl': 'assets/images/addis_img_2.avif',
    'company': 'Addidas',
    'sizes': [9, 10, 12],
  },
  {
    'id': '2',
    'title': 'Bata Women\'s Shoes',
    'price': 28.95,
    'imageUrl': 'assets/images/image_2.jpg',
    'company': 'Bata',
    'sizes': [8, 9, 10],
  },
  {
    'id': '3',
    'title': 'Jordan Shoes',
    'price': 120.69,
    'imageUrl': 'assets/images/addis_image_1.avif',
    'company': 'Addidas',
    'sizes': [8, 9, 10],
  },
  {
    'id': '4',
    'title': 'Jordan Shoes',
    'price': 210.69,
    'imageUrl': 'assets/images/image_3.webp',
    'company': 'Nike',
    'sizes': [8, 9, 10],
  },
  {
    'id': '5',
    'title': 'Jordan Shoes',
    'price': 234.69,
    'imageUrl': 'assets/images/image_4.webp',
    'company': 'Nike',
    'sizes': [8, 9, 10],
  },
];
